### ISSUE TITLE
Trying your app but failed

### ISSUE THREAD

**Issue by hocuspocus69** [deepankarvarma/Photo-Collage-Maker-Using-Python#1]
I'm trying your app for an university project but streamlit fail....
have you any idea how to correct it?
Thank you

**Comment by deepankarvarma** [comment]
It’s working now. Head on to https://deepankarvarma-photo-collage-maker-using-python-app-v4whb9.streamlit.app/

**Comment by hocuspocus69** [comment]
I'm trying just now and it's not working with 3x3 tile

**Comment by hocuspocus69** [comment]
Sorry my mistake too large image size 8000x7000
